declare module '@sbol/design-system/core/icon/cards/*.svg' {
    const icon: string
    export default icon
}

declare module '@sbol/design-system/core/icon/cards' {
    export const mc36AmericanexpressLogo: string
    export const mc36AmexCredit: string
    export const mc36AmexPremium: string
    export const mc36CardLock: string
    export const mc36Default: string
    export const mc36MaestroClassic: string
    export const mc36MaestroLogo: string
    export const mc36MaestroMomentum: string
    export const mc36MaestroSocial: string
    export const mc36MaestroStudent: string
    export const mc36MastercardBigBonusCredit: string
    export const mc36MastercardBlackEdition: string
    export const mc36MastercardBusinessBudget: string
    export const mc36MastercardBusinessCredit: string
    export const mc36MastercardBusiness: string
    export const mc36MastercardClassicCredit: string
    export const mc36MastercardDigitalBusiness: string
    export const mc36MastercardDigitalCredit2: string
    export const mc36MastercardDigitalCredit: string
    export const mc36MastercardGoldCredit: string
    export const mc36MastercardGoldSber: string
    export const mc36MastercardGold: string
    export const mc36MastercardIno: string
    export const mc36MastercardLogo: string
    export const mc36MastercardMomentumBusinessCredit: string
    export const mc36MastercardMomentumBusiness: string
    export const mc36MastercardMomentumCredit: string
    export const mc36MastercardMomentumSocial: string
    export const mc36MastercardMomentum: string
    export const mc36MastercardPlatinum: string
    export const mc36MastercardPreferredBusiness: string
    export const mc36MastercardSbercardLevel1: string
    export const mc36MastercardSbercardLevel2: string
    export const mc36MastercardSbercardLevel3: string
    export const mc36MastercardSbercardLevel4: string
    export const mc36MastercardSberkids: string
    export const mc36MastercardTeenage: string
    export const mc36MastercardTravelLevel1: string
    export const mc36MastercardTravelLevel2: string
    export const mc36MastercardTravelLevel3: string
    export const mc36MastercardTravelLevel4: string
    export const mc36MastercardWeliteSbercard: string
    export const mc36Mastercard: string
    export const mc36McVirtual: string
    export const mc36Mir2: string
    export const mc36MirGold: string
    export const mc36MirLogo2: string
    export const mc36MirLogo: string
    export const mc36MirMomentum: string
    export const mc36MirPlatinum: string
    export const mc36MirSbercardLevel1: string
    export const mc36MirSbercardLevel2: string
    export const mc36MirSbercardLevel3: string
    export const mc36MirSbercardLevel4: string
    export const mc36MirSocial: string
    export const mc36Mir: string
    export const mc36Pro100Logo: string
    export const mc36Pro100Standart: string
    export const mc36Travel: string
    export const mc36UekLogo: string
    export const mc36VisaBigBonusCredit: string
    export const mc36VisaBusinessCredit: string
    export const mc36VisaBusiness: string
    export const mc36VisaClassicCredit: string
    export const mc36VisaClassicGiveLife: string
    export const mc36VisaCska: string
    export const mc36VisaDigital2: string
    export const mc36VisaDigitalBusiness: string
    export const mc36VisaDigitalCredit2: string
    export const mc36VisaDigitalCredit: string
    export const mc36VisaDigitalOld: string
    export const mc36VisaDigital: string
    export const mc36VisaElectron2: string
    export const mc36VisaElectron: string
    export const mc36VisaGoldCredit: string
    export const mc36VisaGoldGiveLife: string
    export const mc36VisaGoldSber: string
    export const mc36VisaGold: string
    export const mc36VisaInfinitePb: string
    export const mc36VisaInfinitySbercard: string
    export const mc36VisaInfinity: string
    export const mc36VisaLogo: string
    export const mc36VisaMomentumBusinessCredit: string
    export const mc36VisaMomentumBusiness: string
    export const mc36VisaMomentumCredit: string
    export const mc36VisaMomentum: string
    export const mc36VisaPb1: string
    export const mc36VisaPb2: string
    export const mc36VisaPlatinumBusiness: string
    export const mc36VisaPlatinumGiveLife: string
    export const mc36VisaPlatinum: string
    export const mc36VisaPremium: string
    export const mc36VisaSbercardLevel1: string
    export const mc36VisaSbercardLevel2: string
    export const mc36VisaSbercardLevel3: string
    export const mc36VisaSbercardLevel4: string
    export const mc36VisaTeenage: string
    export const mc36VisaTravelLevel1: string
    export const mc36VisaTravelLevel2: string
    export const mc36VisaTravelLevel3: string
    export const mc36VisaTravelLevel4: string
    export const mc36VisaVirtual: string
    export const mc36Visa: string
}
