declare module '@sbol/design-system/core/icon/common/*.svg' {
    const icon: string
    export default icon
}

declare module '@sbol/design-system/core/icon/common' {
    export const combinedShape: string
    export const externalBold: string
    export const externalRegular: string
    export const ic24Airflow: string
    export const ic24ArrowClockwise: string
    export const ic24ArrowLeft: string
    export const ic24ArrowLeftAlt1: string
    export const ic24ArrowRightCircle: string
    export const ic24ArrowRightRectangle: string
    export const ic24ArrowRightSquare: string
    export const ic24ArrowRightUturn: string
    export const ic24ArrowRight: string
    export const ic24ArrowRightAlt1: string
    export const ic24Bag: string
    export const ic24BellCrossed: string
    export const ic24Bell: string
    export const ic24Bolt: string
    export const ic24Building: string
    export const ic24Calendar: string
    export const ic24CardGrid: string
    export const ic24Card: string
    export const ic24Cart: string
    export const ic24Check: string
    export const ic24CheckmarkCircle: string
    export const ic24ChevronDown: string
    export const ic24ChevronLeft: string
    export const ic24ChevronRight: string
    export const ic24ChevronUp: string
    export const ic24ClockFill: string
    export const ic24ClockStroke: string
    export const ic24CoinDown: string
    export const ic24CrossCircle: string
    export const ic24CrossSmall: string
    export const ic24Cross: string
    export const ic24DotsHorizontal: string
    export const ic24DotsVertical: string
    export const ic24ExclamationFill: string
    export const ic24Exclamation: string
    export const ic24EyeCross: string
    export const ic24Eye: string
    export const ic24Filter: string
    export const ic24Flag: string
    export const ic24Flame: string
    export const ic24Funnel: string
    export const ic24Gear: string
    export const ic24House: string
    export const ic24InfoCircle: string
    export const ic24Info: string
    export const ic24Letter: string
    export const ic24List: string
    export const ic24LockCross: string
    export const ic24Lock: string
    export const ic24MagnifyingGlass: string
    export const ic24Map: string
    export const ic24Meter: string
    export const ic24Mic: string
    export const ic24MicrophoneCross: string
    export const ic24Moon: string
    export const ic24Number: string
    export const ic24PencilLine: string
    export const ic24PencilStroke: string
    export const ic24Pencil: string
    export const ic24Percent: string
    export const ic24PhoneHanging: string
    export const ic24Phone: string
    export const ic24PhotocameraCounterClockwise: string
    export const ic24Pillow: string
    export const ic24PinCrossed: string
    export const ic24Pin: string
    export const ic24Plane: string
    export const ic24Plus: string
    export const ic24Qr: string
    export const ic24Safe: string
    export const ic24SberAlt1: string
    export const ic24Sber: string
    export const ic24Snowflake: string
    export const ic24Spasibo: string
    export const ic24SpeakerCross: string
    export const ic24Speaker: string
    export const ic24SpeechBubble: string
    export const ic24Stack: string
    export const ic24Sun: string
    export const ic24Target: string
    export const ic24Text: string
    export const ic24Thermometer: string
    export const ic24TrashBin: string
    export const ic24Trashbin: string
    export const ic24UserOnUser: string
    export const ic24UserStroke: string
    export const ic24User: string
    export const ic24VideocameraCross: string
    export const ic24Videocamera: string
    export const ic24Wallet: string
    export const ic36AppleWallet: string
    export const ic36ArmyOfRussia: string
    export const ic36ArrowClockwise: string
    export const ic36ArrowLeftFill: string
    export const ic36ArrowRightChevronRectangle: string
    export const ic36ArrowRightTraceLineFill: string
    export const ic36ArrowRightTraceLine: string
    export const ic36ArrowUturnFill: string
    export const ic36ArrowUturnLeft: string
    export const ic36ArrowsForwardBackFill: string
    export const ic36ArrowsForwardBack: string
    export const ic36ArrowsUpDown: string
    export const ic36AsteriskFill: string
    export const ic36Asv: string
    export const ic36AtmBanknote: string
    export const ic36Backpack: string
    export const ic36BagFill: string
    export const ic36Bag: string
    export const ic36Balloon: string
    export const ic36BallotPaper: string
    export const ic36Banknote: string
    export const ic36BarGraphFill: string
    export const ic36BarGraph: string
    export const ic36BasketFill: string
    export const ic36Basket: string
    export const ic36BeachUmbrella: string
    export const ic36Beanie: string
    export const ic36Beard: string
    export const ic36BellCrossFill: string
    export const ic36BellCrossed: string
    export const ic36BellFill: string
    export const ic36Bell: string
    export const ic36BetaCircle: string
    export const ic36BoardingPass: string
    export const ic36BoltFill: string
    export const ic36Bolt: string
    export const ic36BookmarkFill: string
    export const ic36Box: string
    export const ic36Brooch: string
    export const ic36BuildingFill: string
    export const ic36Building: string
    export const ic36BusFill: string
    export const ic36Bus: string
    export const ic36Calculator: string
    export const ic36CalculatorFill: string
    export const ic36CalendarCheckmark: string
    export const ic36CalendarFill: string
    export const ic36CalendarGraph: string
    export const ic36Calendar: string
    export const ic36Camera: string
    export const ic36Candy: string
    export const ic36Capsule: string
    export const ic36CarFill: string
    export const ic36Car: string
    export const ic36CardChevronLeftFill: string
    export const ic36CardChevronLeft: string
    export const ic36CardCounterClockwise: string
    export const ic36CardCrossFill: string
    export const ic36CardCross: string
    export const ic36CardCvcFill: string
    export const ic36CardFill: string
    export const ic36CardGrid: string
    export const ic36CardOnCardFill: string
    export const ic36CardOnCard: string
    export const ic36CardPlus: string
    export const ic36CardVanishes: string
    export const ic36CardViewfinder: string
    export const ic36Card: string
    export const ic36CardsCarousel: string
    export const ic36CaseCrossFill: string
    export const ic36CaseDiagramFill: string
    export const ic36CaseDiagram: string
    export const ic36CaseFill: string
    export const ic36Case: string
    export const ic36CashFill: string
    export const ic36CheckmarkAlt1: string
    export const ic36Checkmark: string
    export const ic36Cheekbones: string
    export const ic36ChessPieceFill: string
    export const ic36ChessPiece: string
    export const ic36ChevronDown: string
    export const ic36ChevronUp: string
    export const ic36Chin: string
    export const ic36CircleCross: string
    export const ic36CircleCrossedFill: string
    export const ic36CirclePlus: string
    export const ic36Clock: string
    export const ic36CloudFill: string
    export const ic36CoatOfArmsFill: string
    export const ic36CoatOfArms: string
    export const ic36CoinDown: string
    export const ic36CoinFill: string
    export const ic36CoinHeart: string
    export const ic36Coin: string
    export const ic36Collar: string
    export const ic36Contrast: string
    export const ic36Cosmetic: string
    export const ic36CounterClockwiseFill: string
    export const ic36CounterClockwiseRuble: string
    export const ic36CounterClockwise: string
    export const ic36CouponFill: string
    export const ic36Coupon: string
    export const ic36Crest: string
    export const ic36Cross: string
    export const ic36Crown: string
    export const ic36CutleryFill: string
    export const ic36Cutlery: string
    export const ic36DigitalBanknotes: string
    export const ic36Dna: string
    export const ic36DocumentChartFill: string
    export const ic36DocumentCheckmark: string
    export const ic36DocumentFill: string
    export const ic36DocumentMagnifyingGlass: string
    export const ic36DocumentOnDocument: string
    export const ic36Document: string
    export const ic36DoubleArrowUturnRight: string
    export const ic36Drop: string
    export const ic36EarCross: string
    export const ic36Ear: string
    export const ic36EllipsViewfinderFill: string
    export const ic36EllipsViewfinder: string
    export const ic36Exclamation: string
    export const ic36EyeAlt12: string
    export const ic36EyeAlt1: string
    export const ic36EyeCrossed: string
    export const ic36Eye: string
    export const ic36Eyebrows: string
    export const ic36Eyelashes: string
    export const ic36FaceId: string
    export const ic36FaceOval: string
    export const ic36Face: string
    export const ic36FallingCoin: string
    export const ic36FileChart: string
    export const ic36FileExcel: string
    export const ic36FilePdf: string
    export const ic36Fingerprint: string
    export const ic36Flag: string
    export const ic36Flame: string
    export const ic36FlasherFill: string
    export const ic36Flasher: string
    export const ic36FoodPlateFill: string
    export const ic36Funnel: string
    export const ic36Gamepad2: string
    export const ic36Gamepad: string
    export const ic36GasStationFill: string
    export const ic36GavelFill: string
    export const ic36Gear: string
    export const ic36GiftFill: string
    export const ic36Gift: string
    export const ic36GlassesFill: string
    export const ic36Glasses: string
    export const ic36GlobeFill: string
    export const ic36Globe: string
    export const ic36Gosuslugi: string
    export const ic36Hair: string
    export const ic36Hammer: string
    export const ic36Handset: string
    export const ic36Hanger: string
    export const ic36HeadQuestion: string
    export const ic36Headphones: string
    export const ic36HeartFill: string
    export const ic36HeartHand: string
    export const ic36HeartHandFill: string
    export const ic36Heart: string
    export const ic36HelmetFill: string
    export const ic36HouseFill: string
    export const ic36HouseGasFill: string
    export const ic36HouseHandset: string
    export const ic36HousePercentFill: string
    export const ic36HousePercent: string
    export const ic36House: string
    export const ic36IdCardFill: string
    export const ic36IdDocumentFill: string
    export const ic36Infinity: string
    export const ic36Info: string
    export const ic36IngotFill: string
    export const ic36Ingot: string
    export const ic36Jacket: string
    export const ic36KeyFill: string
    export const ic36Key: string
    export const ic36KeyboardDown: string
    export const ic36LettersAa: string
    export const ic36LinkFill: string
    export const ic36Link: string
    export const ic36Lips: string
    export const ic36ListCheckmark: string
    export const ic36List: string
    export const ic36LockClosedFill: string
    export const ic36LockClosed: string
    export const ic36LockOpenedAlt1: string
    export const ic36LockOpenedFill: string
    export const ic36LockOpened: string
    export const ic36MagicWand: string
    export const ic36Magnit: string
    export const ic36MailEye: string
    export const ic36MailFill: string
    export const ic36MailWaves: string
    export const ic36Mail: string
    export const ic36ManBadge: string
    export const ic36ManFill: string
    export const ic36ManWheelchair: string
    export const ic36Map: string
    export const ic36Mask: string
    export const ic36Medal: string
    export const ic36MedicineFill: string
    export const ic36Meteorite: string
    export const ic36MeterFill: string
    export const ic36Mindmap: string
    export const ic36MobileFill: string
    export const ic36MobilePlusAlt: string
    export const ic36MobilePlus: string
    export const ic36MobileWaves: string
    export const ic36Mobile: string
    export const ic36MoneybagFill: string
    export const ic36Moneybag: string
    export const ic36MoonStarsFill: string
    export const ic36MoonStars: string
    export const ic36Necklace: string
    export const ic36Nose: string
    export const ic36Note: string
    export const ic36NotebookWaves: string
    export const ic36OkkoFill: string
    export const ic36OpenBook: string
    export const ic36PadFill: string
    export const ic36PaletteFill: string
    export const ic36PaperTray: string
    export const ic36Parking: string
    export const ic36Passport: string
    export const ic36PauseFill: string
    export const ic36Pause: string
    export const ic36PawFill: string
    export const ic36Paw: string
    export const ic36PencilCross: string
    export const ic36PencilFill: string
    export const ic36PencilLine: string
    export const ic36PercentFill: string
    export const ic36Percent: string
    export const ic36Photo: string
    export const ic36PictureFill: string
    export const ic36PieChartFill: string
    export const ic36PieChart: string
    export const ic36PiechartSector: string
    export const ic36Piercing: string
    export const ic36PinFill: string
    export const ic36PlaneFill: string
    export const ic36Plane: string
    export const ic36PlayAlt1Fill: string
    export const ic36PlayFill: string
    export const ic36Play: string
    export const ic36PostcardHeart: string
    export const ic36PramFill: string
    export const ic36Pram: string
    export const ic36QrCode: string
    export const ic36QuickPaymentSystem: string
    export const ic36ReceiptFill: string
    export const ic36Receipt: string
    export const ic36RectangleOnDashedRectangle: string
    export const ic36RectangleSpeechBubbleFill: string
    export const ic36RectangleSpeechBubbleList: string
    export const ic36RectangleSpeechBubbleOnSpeechBubble: string
    export const ic36RectangleSpeechBubble: string
    export const ic36RectangleWatches: string
    export const ic36RedCross: string
    export const ic36Rocket: string
    export const ic36RoundSpeechBubbleArrowUp: string
    export const ic36RoundSpeechBubbleCheckmark: string
    export const ic36RoundSpeechBubbleCross: string
    export const ic36RoundSpeechBubbleExclamation: string
    export const ic36RoundSpeechBubbleQuestion: string
    export const ic36RoundWatches: string
    export const ic36Route: string
    export const ic36RubleDollar: string
    export const ic36RublePlus: string
    export const ic36Ruler: string
    export const ic36SafeAlt: string
    export const ic36SafeArrowDownLeftFill: string
    export const ic36SafeArrowUpRightFill: string
    export const ic36SafeCrossFill: string
    export const ic36SafeDiagram: string
    export const ic36SafeFill: string
    export const ic36Safe: string
    export const ic36SberLogoFill: string
    export const ic36Sber: string
    export const ic36SberbankId: string
    export const ic36Sbermiles: string
    export const ic36SbermobileFill: string
    export const ic36Sberpay: string
    export const ic36Scales: string
    export const ic36ScissorsFill: string
    export const ic36SecurityCamera: string
    export const ic36ShieldCheck: string
    export const ic36ShieldCrossed: string
    export const ic36ShieldFill: string
    export const ic36ShieldLinesCircles: string
    export const ic36ShieldLinesFill: string
    export const ic36ShieldLines: string
    export const ic36Shield: string
    export const ic36ShirtFill: string
    export const ic36Shirt: string
    export const ic36SimCard: string
    export const ic36SmileAffable: string
    export const ic36SmileGlad: string
    export const ic36SmileHappy: string
    export const ic36SmileSad: string
    export const ic36SmileSullen: string
    export const ic36SpasiboFill: string
    export const ic36Spasibo: string
    export const ic36SpeakerWaves: string
    export const ic36SpeedometerFill: string
    export const ic36Speedometer: string
    export const ic36SquareOnSquare: string
    export const ic36StarFill: string
    export const ic36StarLightFill: string
    export const ic36StarLight: string
    export const ic36Star: string
    export const ic36SteeringWheel: string
    export const ic36StudentHatFill: string
    export const ic36StudentHat: string
    export const ic36SwitchOffFill: string
    export const ic36SwitchOnFill: string
    export const ic36TableLampFill: string
    export const ic36TableLamp: string
    export const ic36Tag: string
    export const ic36Tap: string
    export const ic36TaxiFill: string
    export const ic36Telephone: string
    export const ic36Thermometer: string
    export const ic36ThreeDotsFill: string
    export const ic36Trash: string
    export const ic36TrayDown: string
    export const ic36Truck: string
    export const ic36TvSet: string
    export const ic36UmbrellaFill: string
    export const ic36Umbrella: string
    export const ic36UserCross: string
    export const ic36UserFill: string
    export const ic36UserOnUser: string
    export const ic36UserPlus: string
    export const ic36User: string
    export const ic36VialFill: string
    export const ic36Vial: string
    export const ic36Vibration: string
    export const ic36Videocamera: string
    export const ic36WalletCheckFill: string
    export const ic36WalletFill: string
    export const ic36WalletLines: string
    export const ic36Wallet: string
    export const ic36WaterPipe: string
    export const ic36WateringCan: string
    export const ic36WavesCross: string
    export const ic36Waves: string
    export const ic36WhistleFill: string
    export const ic36Whistle: string
    export const ic36Wrench: string
    export const ic36Yule: string
    export const info: string
    export const minus: string
    export const plus: string
    export const success: string
    export const waiting: string
    export const warning: string
    export const playStory: string
}
