declare module '@sbol/design-system/core/icon/countries/*.svg' {
    const icon: string
    export default icon
}

declare module '@sbol/design-system/core/icon/countries' {
    export const mc36BritishVirginIslands: string
    export const mc36FlagAbkhazia: string
    export const mc36FlagAfghanistan: string
    export const mc36FlagAlandIsland: string
    export const mc36FlagAlbania: string
    export const mc36FlagAlgeria: string
    export const mc36FlagAndorra: string
    export const mc36FlagAngola: string
    export const mc36FlagAntiguaAndBarbuda: string
    export const mc36FlagArgentina: string
    export const mc36FlagArmenia: string
    export const mc36FlagAruba: string
    export const mc36FlagAustralia: string
    export const mc36FlagAustria: string
    export const mc36FlagAzerbaijan: string
    export const mc36FlagBahamas: string
    export const mc36FlagBahrain: string
    export const mc36FlagBangladesh: string
    export const mc36FlagBarbados: string
    export const mc36FlagBelarus: string
    export const mc36FlagBelgium: string
    export const mc36FlagBelize: string
    export const mc36FlagBenin: string
    export const mc36FlagBhutan: string
    export const mc36FlagBolivia: string
    export const mc36FlagBosniaAndHerzegovina: string
    export const mc36FlagBotswana: string
    export const mc36FlagBrazil: string
    export const mc36FlagBrunei: string
    export const mc36FlagBulgaria: string
    export const mc36FlagBurkinaFaso: string
    export const mc36FlagBurundi: string
    export const mc36FlagCambodia: string
    export const mc36FlagCameroon: string
    export const mc36FlagCanada: string
    export const mc36FlagCapeVerde: string
    export const mc36FlagCentralAfricanRepublic: string
    export const mc36FlagChad: string
    export const mc36FlagChile: string
    export const mc36FlagChina: string
    export const mc36FlagColombia: string
    export const mc36FlagComoros: string
    export const mc36FlagCongoDemocraticRepublic: string
    export const mc36FlagCongo: string
    export const mc36FlagCostaRica: string
    export const mc36FlagCoteDIvoire: string
    export const mc36FlagCroatia: string
    export const mc36FlagCuba: string
    export const mc36FlagCyprus: string
    export const mc36FlagCzechRepublic: string
    export const mc36FlagDenmark: string
    export const mc36FlagDjibouti: string
    export const mc36FlagDominica: string
    export const mc36FlagDominicanRepublic: string
    export const mc36FlagEastTimor: string
    export const mc36FlagEcuador: string
    export const mc36FlagEgypt: string
    export const mc36FlagEngland: string
    export const mc36FlagEquatorialGuinea: string
    export const mc36FlagEritrea: string
    export const mc36FlagEstonia: string
    export const mc36FlagEthiopia: string
    export const mc36FlagEurope: string
    export const mc36FlagFaeroes: string
    export const mc36FlagFiji: string
    export const mc36FlagFinland: string
    export const mc36FlagFrance: string
    export const mc36FlagFrenchPolynesia: string
    export const mc36FlagGabon: string
    export const mc36FlagGambia: string
    export const mc36FlagGeorgia: string
    export const mc36FlagGermany: string
    export const mc36FlagGhana: string
    export const mc36FlagGibraltar: string
    export const mc36FlagGreece: string
    export const mc36FlagGreenland: string
    export const mc36FlagGrenada: string
    export const mc36FlagGuatemala: string
    export const mc36FlagGuineaBissau: string
    export const mc36FlagGuinea: string
    export const mc36FlagGuyana: string
    export const mc36FlagHaiti: string
    export const mc36FlagHonduras: string
    export const mc36FlagHongKong: string
    export const mc36FlagHungary: string
    export const mc36FlagIceland: string
    export const mc36FlagIndia: string
    export const mc36FlagIndonesia: string
    export const mc36FlagIran: string
    export const mc36FlagIraq: string
    export const mc36FlagIreland: string
    export const mc36FlagIsleOfMan: string
    export const mc36FlagIsrael: string
    export const mc36FlagItaly: string
    export const mc36FlagJamaica: string
    export const mc36FlagJapan: string
    export const mc36FlagJersey: string
    export const mc36FlagJordan: string
    export const mc36FlagKazakhstan: string
    export const mc36FlagKenya: string
    export const mc36FlagKiribati: string
    export const mc36FlagKosovo: string
    export const mc36FlagKurasao: string
    export const mc36FlagKuwait: string
    export const mc36FlagKyrgyzstan: string
    export const mc36FlagLaos: string
    export const mc36FlagLatvia: string
    export const mc36FlagLebanon: string
    export const mc36FlagLesotho: string
    export const mc36FlagLiberia: string
    export const mc36FlagLibya: string
    export const mc36FlagLiechtenstein: string
    export const mc36FlagLithuania: string
    export const mc36FlagLuxembourg: string
    export const mc36FlagMacao: string
    export const mc36FlagMacedonia: string
    export const mc36FlagMadagascar: string
    export const mc36FlagMalawi: string
    export const mc36FlagMalaysia: string
    export const mc36FlagMaldives: string
    export const mc36FlagMali: string
    export const mc36FlagMalta: string
    export const mc36FlagMarshallIslands: string
    export const mc36FlagMauritania: string
    export const mc36FlagMauritius: string
    export const mc36FlagMexico: string
    export const mc36FlagMicronesia: string
    export const mc36FlagMoldova: string
    export const mc36FlagMonaco: string
    export const mc36FlagMongolia: string
    export const mc36FlagMontenegro: string
    export const mc36FlagMorocco: string
    export const mc36FlagMozambique: string
    export const mc36FlagMyanmar: string
    export const mc36FlagNamibia: string
    export const mc36FlagNauru: string
    export const mc36FlagNepal: string
    export const mc36FlagNetherlands: string
    export const mc36FlagNewZealand: string
    export const mc36FlagNicaragua: string
    export const mc36FlagNiger: string
    export const mc36FlagNigeria: string
    export const mc36FlagNiue: string
    export const mc36FlagNone: string
    export const mc36FlagNorthKorea: string
    export const mc36FlagNorway: string
    export const mc36FlagOman: string
    export const mc36FlagPakistan: string
    export const mc36FlagPalau: string
    export const mc36FlagPanama: string
    export const mc36FlagPapuaNewGuinea: string
    export const mc36FlagParaguay: string
    export const mc36FlagPeru: string
    export const mc36FlagPhilippines: string
    export const mc36FlagPoland: string
    export const mc36FlagPortugal: string
    export const mc36FlagPuertoRico: string
    export const mc36FlagQatar: string
    export const mc36FlagRomania: string
    export const mc36FlagRussia: string
    export const mc36FlagRwanda: string
    export const mc36FlagSaintKittsAndNevis: string
    export const mc36FlagSaintLucia: string
    export const mc36FlagSaintVincentAndTheGrenadines: string
    export const mc36FlagSalvador: string
    export const mc36FlagSamoa: string
    export const mc36FlagSanMarino: string
    export const mc36FlagSaoTomeAndPrincipe: string
    export const mc36FlagSaudiArabia: string
    export const mc36FlagSenegal: string
    export const mc36FlagSerbia: string
    export const mc36FlagSeychelles: string
    export const mc36FlagSierraLeone: string
    export const mc36FlagSingapore: string
    export const mc36FlagSlovakia: string
    export const mc36FlagSlovenia: string
    export const mc36FlagSolomonIslands: string
    export const mc36FlagSomalia: string
    export const mc36FlagSouthAfrica: string
    export const mc36FlagSouthKorea: string
    export const mc36FlagSouthOsetia: string
    export const mc36FlagSouthSudan: string
    export const mc36FlagSpain: string
    export const mc36FlagSriLanka: string
    export const mc36FlagSudan: string
    export const mc36FlagSuriname: string
    export const mc36FlagSwaziland: string
    export const mc36FlagSweden: string
    export const mc36FlagSwitzerland: string
    export const mc36FlagSyria: string
    export const mc36FlagTaiwan: string
    export const mc36FlagTajikistan: string
    export const mc36FlagTanzania: string
    export const mc36FlagThailand: string
    export const mc36FlagTogo: string
    export const mc36FlagTonga: string
    export const mc36FlagTrinidadAndTobago: string
    export const mc36FlagTunisia: string
    export const mc36FlagTurkey: string
    export const mc36FlagTurkmenistan: string
    export const mc36FlagTuvalu: string
    export const mc36FlagUganda: string
    export const mc36FlagUkraine: string
    export const mc36FlagUnitedArabEmirates: string
    export const mc36FlagUnitedKingdom: string
    export const mc36FlagUruguay: string
    export const mc36FlagUsa: string
    export const mc36FlagUzbekistan: string
    export const mc36FlagVanuatu: string
    export const mc36FlagVatican: string
    export const mc36FlagVenezuela: string
    export const mc36FlagVietnam: string
    export const mc36FlagYemen: string
    export const mc36FlagZambia: string
    export const mc36FlagZimbabwe: string
}
